// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRV3UMwopVCPJyd32K-_1CMJQaTeYachw',
    appId: '1:143934639674:web:43860587e69c3f2d2f6f03',
    messagingSenderId: '143934639674',
    projectId: 'klf-brown',
    authDomain: 'klf-brown.firebaseapp.com',
    storageBucket: 'klf-brown.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4lD3l_GtExSwPCpscTMR4KmZHD5SmZnQ',
    appId: '1:143934639674:android:2dfc39eb309459c32f6f03',
    messagingSenderId: '143934639674',
    projectId: 'klf-brown',
    storageBucket: 'klf-brown.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxl97FcNEVpVZLEXv_c5z3CX4h8-WLKyc',
    appId: '1:143934639674:ios:914603fa82cab3b52f6f03',
    messagingSenderId: '143934639674',
    projectId: 'klf-brown',
    storageBucket: 'klf-brown.firebasestorage.app',
    iosBundleId: 'com.example.klfBrown',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxl97FcNEVpVZLEXv_c5z3CX4h8-WLKyc',
    appId: '1:143934639674:ios:914603fa82cab3b52f6f03',
    messagingSenderId: '143934639674',
    projectId: 'klf-brown',
    storageBucket: 'klf-brown.firebasestorage.app',
    iosBundleId: 'com.example.klfBrown',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRV3UMwopVCPJyd32K-_1CMJQaTeYachw',
    appId: '1:143934639674:web:3135ad2525237e212f6f03',
    messagingSenderId: '143934639674',
    projectId: 'klf-brown',
    authDomain: 'klf-brown.firebaseapp.com',
    storageBucket: 'klf-brown.firebasestorage.app',
  );
}
